name: Publish and deploy the application to Google Cloud resources
on:
  push:
    branches:
      - master
jobs:
  publish-app-to-gcp-artifact:
    uses: ./.github/workflows/publish-image-to-gar.yaml
    secrets: inherit
  deploy-app-to-cloudrun:
    needs:
      - publish-app-to-gcp-artifact
    uses: ./.github/workflows/deploy-app-to-cloudrun.yaml
    with:
      region: 'asia-southeast2'
    secrets: inherit
