name: Build and deploy Book App
env:
  region: asia-southeast2
  target_env: prod
on:
  push:
    branches:
      - master
jobs:
  publish-to-github:
    uses: ./.github/workflows/publish-to-github.yaml
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout the project source code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: gcp_auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCT }}
      - name: Setup GCP CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 485.0.0'
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/book-app:latest
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy book-app --image=${{ env.region }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/book-app:latest \
          --region=${{ env.region }} --min-instances=1 --max-instances=1 --set-env-vars=TARGET_ENV=${{ env.target_env }} \
          --port 8080 --allow-unauthenticated --service-account=${{ secrets.SERVICE_ACCT }}
