name: publish-image-to-github
on:
  workflow_run:
    types: [completed]
    workflows: [unit-tests]

jobs:
  build-and-publish-image-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/lonecalvary78/book-app:latest
