name: Publish to Github Container Registry
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
        default: 'latest'
jobs:
  build-and-publish:
    env:
      target_registry: ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.target_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.target_registry }}/${{ github.actor }}/book-app:${{ inputs.version }}