name: Publish and deploy the application to Google Cloud resources
on:
  push:
    branches:
      - master
jobs:
  publish-app-to-gcp-artifact:
    uses: ./.github/workflows/publish-image-to-gar.yaml
    secrets: inherit
  deploy-app-to-cloudrun:
    env:
      resource_region: 'asia-southeast2'
    needs:
      - publish-app-to-gcp-artifact
    uses: ./.github/workflows/publish-image-to-gar.yaml
    with:
      region: ${{ env.asia-southeast2 }}
    secrets: inherit
