name: Build And Publish to GCP Artifact
on:
  workflow_call:
    inputs:
      region:
        type: string
        required: false
        default: 'us-central1'
      version:
        type: string
        required: false
        default: 'latest'
jobs:
  publish-to-gcp-artifiact:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - id: auth-to-gcp
        name: Authenticate to GCP resources
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCT }}
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth-to-gcp.outputs.access_token }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ inputs.region }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/book-app:${{ inputs.version }}

