name: unit-tests
on:
  workflow_call:
    inputs:
      env_profile:
        type: string
        required: true
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: perform unit test through maven command
        run: mvn clean test -Dquarkus.profile=${{ inputs.env_profile }}